# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(939, 639)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 941, 651))
        self.label.setStyleSheet("background-image: url(:/OTRO/rotacion-de-cultivos-1200x675.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 941, 641))
        self.label_2.setStyleSheet("\n"
"background-color:rgba(0,0,0,230);\n"
"\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 941, 51))
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.frameh = QtWidgets.QFrame(self.widget)
        self.frameh.setGeometry(QtCore.QRect(10, 10, 41, 31))
        self.frameh.setStyleSheet("image: url(:/ICOONO/menu.png);")
        self.frameh.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameh.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameh.setObjectName("frameh")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setGeometry(QtCore.QRect(660, 0, 271, 41))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.notificacion1 = QtWidgets.QPushButton(self.frame_2)
        self.notificacion1.setGeometry(QtCore.QRect(180, 10, 51, 23))
        self.notificacion1.setStyleSheet("color: rgb(255, 255, 255);")
        self.notificacion1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/BELL3/bell (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.notificacion1.setIcon(icon)
        self.notificacion1.setObjectName("notificacion1")
        self.usuario1 = QtWidgets.QPushButton(self.frame_2)
        self.usuario1.setGeometry(QtCore.QRect(230, 10, 31, 21))
        self.usuario1.setStyleSheet("color: rgb(255, 255, 255);")
        self.usuario1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/PERS/person.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.usuario1.setIcon(icon1)
        self.usuario1.setIconSize(QtCore.QSize(24, 24))
        self.usuario1.setObjectName("usuario1")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(80, 0, 101, 51))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Tw Cen MT\";")
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 40, 271, 591))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.enfermedades = QtWidgets.QPushButton(self.frame)
        self.enfermedades.setGeometry(QtCore.QRect(40, 180, 181, 51))
        self.enfermedades.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/eNFERME/virus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.enfermedades.setIcon(icon2)
        self.enfermedades.setIconSize(QtCore.QSize(50, 50))
        self.enfermedades.setObjectName("enfermedades")
        self.plagas = QtWidgets.QPushButton(self.frame)
        self.plagas.setGeometry(QtCore.QRect(40, 290, 151, 71))
        self.plagas.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/PLAGAS/cucaracha.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.plagas.setIcon(icon3)
        self.plagas.setIconSize(QtCore.QSize(50, 50))
        self.plagas.setObjectName("plagas")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 160, 391, 351))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/NEW/WhatsApp_Image_2023-01-23_at_9.54.58_PM-removebg-preview.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Smart Farm Len"))
        self.enfermedades.setText(_translate("MainWindow", "    Enfermedades"))
        self.plagas.setText(_translate("MainWindow", "      Plagas"))
import source2_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
