# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_2_0.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(942, 725)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 941, 731))
        self.label.setStyleSheet("background-image: url(:/OTRO/rotacion-de-cultivos-1200x675.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-20, -10, 971, 741))
        self.label_2.setStyleSheet("\n"
"background-color:rgba(0,0,0,230);\n"
"\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 941, 51))
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.Menuprincipal = QtWidgets.QFrame(self.widget)
        self.Menuprincipal.setGeometry(QtCore.QRect(10, 10, 41, 31))
        self.Menuprincipal.setStyleSheet("image: url(:/ICOONO/menu.png);")
        self.Menuprincipal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Menuprincipal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Menuprincipal.setObjectName("Menuprincipal")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setGeometry(QtCore.QRect(660, 0, 271, 41))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Notificacion = QtWidgets.QPushButton(self.frame_2)
        self.Notificacion.setGeometry(QtCore.QRect(180, 10, 51, 23))
        self.Notificacion.setStyleSheet("color: rgb(255, 255, 255);")
        self.Notificacion.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/BELL3/bell (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Notificacion.setIcon(icon)
        self.Notificacion.setObjectName("Notificacion")
        self.Usuario = QtWidgets.QPushButton(self.frame_2)
        self.Usuario.setGeometry(QtCore.QRect(230, 10, 31, 21))
        self.Usuario.setStyleSheet("color: rgb(255, 255, 255);")
        self.Usuario.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/PERS/person.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Usuario.setIcon(icon1)
        self.Usuario.setIconSize(QtCore.QSize(24, 24))
        self.Usuario.setObjectName("Usuario")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(80, 0, 121, 51))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Tw Cen MT\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(390, 30, 371, 81))
        self.label_4.setStyleSheet("\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(500, 620, 291, 41))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color:rgba(0,59,1,160);\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(340, 590, 171, 101))
        self.label_9.setStyleSheet("image: url(:/ALGODON/pexels-cottonbro-studio-4273426.jpg);\n"
"img{ \n"
"   border-radius: 50%;\n"
"}")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.Algodon = QtWidgets.QPushButton(self.centralwidget)
        self.Algodon.setGeometry(QtCore.QRect(580, 650, 75, 23))
        self.Algodon.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.Algodon.setObjectName("Algodon")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(780, 90, 151, 131))
        self.label_10.setStyleSheet("\n"
"image: url(:/PAPA/WhatsApp Image 2023-01-24 at 2.10.26 PM.jpeg);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(790, 200, 131, 131))
        self.label_11.setStyleSheet("image: url(:/JR/trigo.jpg);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(790, 270, 151, 221))
        self.label_12.setStyleSheet("image: url(:/TOMATE/WhatsApp Image 2023-01-24 at 2.13.28 PM.jpeg);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 100, 151, 91))
        self.label_14.setStyleSheet("image: url(:/BANANO/MSC16006700_s.jpg);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(720, 460, 261, 141))
        self.label_18.setStyleSheet("image: url(:/YUCA/WhatsApp Image 2023-01-24 at 2.11.58 PM.jpeg);")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(500, 120, 381, 41))
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color:rgba(0,59,1,160);\n"
"")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(600, 230, 321, 41))
        self.label_20.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color:rgba(0,59,1,160);\n"
"")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(500, 230, 381, 41))
        self.label_21.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color:rgba(0,59,1,160);\n"
"")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(500, 360, 381, 41))
        self.label_22.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color:rgba(0,59,1,160);\n"
"")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(500, 510, 321, 41))
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color:rgba(0,59,1,160);\n"
"")
        self.label_23.setObjectName("label_23")
        self.Papa = QtWidgets.QPushButton(self.centralwidget)
        self.Papa.setGeometry(QtCore.QRect(600, 150, 75, 23))
        self.Papa.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.Papa.setObjectName("Papa")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(100, 120, 341, 41))
        self.label_24.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color:rgba(0,59,1,160);\n"
"")
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(30, 230, 411, 41))
        self.label_25.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color:rgba(0,59,1,160);\n"
"")
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(150, 360, 291, 41))
        self.label_26.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color:rgba(0,59,1,160);\n"
"")
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 280, 161, 191))
        self.label_6.setStyleSheet("image: url(:/tom/cuidados-de-cultivos-de-tomate-encabezado.jpg);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 190, 141, 131))
        self.label_7.setStyleSheet("image: url(:/mma/descarga (4).jfif);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(-10, 470, 221, 111))
        self.label_8.setStyleSheet("image: url(:/CANNA/usos-cana-de-azucar.jpg);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(130, 510, 311, 41))
        self.label_27.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 7pt \"MS Shell Dlg 2\";\n"
"background-color:rgba(0,59,1,160);\n"
"")
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.Trigo = QtWidgets.QPushButton(self.centralwidget)
        self.Trigo.setGeometry(QtCore.QRect(600, 270, 75, 23))
        self.Trigo.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.Trigo.setObjectName("Trigo")
        self.Tomate_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Tomate_2.setGeometry(QtCore.QRect(610, 390, 75, 23))
        self.Tomate_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.Tomate_2.setObjectName("Tomate_2")
        self.Yuca = QtWidgets.QPushButton(self.centralwidget)
        self.Yuca.setGeometry(QtCore.QRect(620, 540, 75, 23))
        self.Yuca.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.Yuca.setObjectName("Yuca")
        self.Canadeazucar = QtWidgets.QPushButton(self.centralwidget)
        self.Canadeazucar.setGeometry(QtCore.QRect(260, 540, 75, 23))
        self.Canadeazucar.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.Canadeazucar.setObjectName("Canadeazucar")
        self.Tomate = QtWidgets.QPushButton(self.centralwidget)
        self.Tomate.setGeometry(QtCore.QRect(280, 390, 75, 23))
        self.Tomate.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.Tomate.setObjectName("Tomate")
        self.Maiz = QtWidgets.QPushButton(self.centralwidget)
        self.Maiz.setGeometry(QtCore.QRect(280, 260, 75, 23))
        self.Maiz.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.Maiz.setObjectName("Maiz")
        self.Banana = QtWidgets.QPushButton(self.centralwidget)
        self.Banana.setGeometry(QtCore.QRect(280, 150, 75, 23))
        self.Banana.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.Banana.setObjectName("Banana")
        self.label_20.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.widget.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_9.raise_()
        self.Algodon.raise_()
        self.label_19.raise_()
        self.label_10.raise_()
        self.label_21.raise_()
        self.label_11.raise_()
        self.label_22.raise_()
        self.label_12.raise_()
        self.label_23.raise_()
        self.label_18.raise_()
        self.Papa.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_14.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_27.raise_()
        self.label_8.raise_()
        self.Trigo.raise_()
        self.Tomate_2.raise_()
        self.Yuca.raise_()
        self.Canadeazucar.raise_()
        self.Tomate.raise_()
        self.Maiz.raise_()
        self.Banana.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Smart Farm Lens"))
        self.label_4.setText(_translate("MainWindow", "MONITOREA TU CULTIVO"))
        self.label_5.setText(_translate("MainWindow", "   Descubre la enfermedad del algodón y como solucionarlo "))
        self.Algodon.setText(_translate("MainWindow", "Analizar"))
        self.label_19.setText(_translate("MainWindow", "     Descubre la enfermedad de la papa y como solucionarlo "))
        self.label_20.setText(_translate("MainWindow", " Descubre la enfermedad del algodón y como solucionarlo "))
        self.label_21.setText(_translate("MainWindow", "    Descubre la enfermedad del trigo y como solucionarlo "))
        self.label_22.setText(_translate("MainWindow", "      Descubre la enfermedad del café y como solucionarlo "))
        self.label_23.setText(_translate("MainWindow", "    Descubre la enfermedad de la yuca y como solucionarlo "))
        self.Papa.setText(_translate("MainWindow", "Analizar"))
        self.label_24.setText(_translate("MainWindow", " Descubre la enfermedad del banano y como solucionarlo    "))
        self.label_25.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "Descubre la enfermedad del maíz y como solucionarlo    "))
        self.label_26.setText(_translate("MainWindow", " Descubre la enfermedad del tomate y como solucionarlo   "))
        self.label_27.setText(_translate("MainWindow", " Descubre la enfermedad del tomate y como solucionarlo  "))
        self.Trigo.setText(_translate("MainWindow", "Analizar"))
        self.Tomate_2.setText(_translate("MainWindow", "Analizar"))
        self.Yuca.setText(_translate("MainWindow", "Analizar"))
        self.Canadeazucar.setText(_translate("MainWindow", "Analizar"))
        self.Tomate.setText(_translate("MainWindow", "Analizar"))
        self.Maiz.setText(_translate("MainWindow", "Analizar"))
        self.Banana.setText(_translate("MainWindow", "Analizar"))
from IMAGENES import source2


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
