# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_2_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 642)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1061, 651))
        self.label.setStyleSheet("background-image: url(:/OTRO/rotacion-de-cultivos-1200x675.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-20, 0, 1091, 641))
        self.label_2.setStyleSheet("\n"
"background-color:rgba(0,0,0,230);\n"
"\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1061, 51))
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.frameh = QtWidgets.QFrame(self.widget)
        self.frameh.setGeometry(QtCore.QRect(10, 10, 41, 31))
        self.frameh.setStyleSheet("image: url(:/ICOONO/menu.png);")
        self.frameh.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameh.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameh.setObjectName("frameh")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setGeometry(QtCore.QRect(660, 0, 271, 41))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(80, 0, 101, 51))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Tw Cen MT\";")
        self.label_3.setObjectName("label_3")
        self.usuario1 = QtWidgets.QPushButton(self.widget)
        self.usuario1.setGeometry(QtCore.QRect(1010, 10, 31, 21))
        self.usuario1.setStyleSheet("color: rgb(255, 255, 255);")
        self.usuario1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PERS/person.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.usuario1.setIcon(icon)
        self.usuario1.setIconSize(QtCore.QSize(24, 24))
        self.usuario1.setObjectName("usuario1")
        self.notificacion1 = QtWidgets.QPushButton(self.widget)
        self.notificacion1.setGeometry(QtCore.QRect(960, 10, 51, 23))
        self.notificacion1.setStyleSheet("color: rgb(255, 255, 255);")
        self.notificacion1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/BELL3/bell (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.notificacion1.setIcon(icon1)
        self.notificacion1.setObjectName("notificacion1")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 50, 271, 591))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.enfermedades = QtWidgets.QPushButton(self.frame)
        self.enfermedades.setGeometry(QtCore.QRect(20, 60, 181, 51))
        self.enfermedades.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/eNFERME/virus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.enfermedades.setIcon(icon2)
        self.enfermedades.setIconSize(QtCore.QSize(50, 50))
        self.enfermedades.setObjectName("enfermedades")
        self.plagas = QtWidgets.QPushButton(self.frame)
        self.plagas.setGeometry(QtCore.QRect(20, 180, 151, 71))
        self.plagas.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/PLAGAS/cucaracha.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.plagas.setIcon(icon3)
        self.plagas.setIconSize(QtCore.QSize(50, 50))
        self.plagas.setObjectName("plagas")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(300, 180, 711, 301))
        self.frame_6.setStyleSheet("background-color:rgb(210, 255, 231);\n"
"font: 14pt \"Arial Rounded MT Bold\";\n"
"border-radius:20px")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.mostrar_con = QtWidgets.QTextEdit(self.frame_6)
        self.mostrar_con.setGeometry(QtCore.QRect(240, 20, 451, 221))
        self.mostrar_con.setStyleSheet("background-color:rgba(106, 106, 106,70);\n"
"border:none;\n"
"border-bottom:2px goldrgba(5,5,5,10);\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:5px;\n"
"")
        self.mostrar_con.setObjectName("mostrar_con")
        self.adjuntar = QtWidgets.QPushButton(self.frame_6)
        self.adjuntar.setGeometry(QtCore.QRect(280, 260, 111, 31))
        self.adjuntar.setStyleSheet("background-color:rgba(106, 106, 106,70);\n"
"border:none;\n"
"border-bottom:2px goldrgba(5,5,5,10);\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:5px;\n"
"")
        self.adjuntar.setObjectName("adjuntar")
        self.predecir = QtWidgets.QPushButton(self.frame_6)
        self.predecir.setGeometry(QtCore.QRect(440, 260, 111, 31))
        self.predecir.setStyleSheet("background-color:rgba(106, 106, 106,70);\n"
"border:none;\n"
"border-bottom:2px goldrgba(5,5,5,10);\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:5px;\n"
"")
        self.predecir.setObjectName("predecir")
        self.eliminar = QtWidgets.QPushButton(self.frame_6)
        self.eliminar.setGeometry(QtCore.QRect(580, 260, 111, 31))
        self.eliminar.setStyleSheet("background-color:rgba(106, 106, 106,70);\n"
"border:none;\n"
"border-bottom:2px goldrgba(5,5,5,10);\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:5px;\n"
"")
        self.eliminar.setObjectName("eliminar")
        self.imagen = QtWidgets.QLabel(self.frame_6)
        self.imagen.setGeometry(QtCore.QRect(40, 30, 201, 251))
        self.imagen.setObjectName("imagen")
        self.Regresar = QtWidgets.QPushButton(self.centralwidget)
        self.Regresar.setGeometry(QtCore.QRect(930, 590, 111, 31))
        self.Regresar.setStyleSheet("background-color:rgba(106, 106, 106,70);\n"
"border:none;\n"
"border-bottom:2px goldrgba(5,5,5,10);\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:5px;\n"
"")
        self.Regresar.setObjectName("Regresar")
        self.ENVIARALCORREO = QtWidgets.QPushButton(self.centralwidget)
        self.ENVIARALCORREO.setGeometry(QtCore.QRect(330, 510, 81, 31))
        self.ENVIARALCORREO.setStyleSheet("background-color:rgba(106, 106, 106,70);\n"
"border:none;\n"
"border-bottom:2px goldrgba(5,5,5,10);\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:5px;\n"
"")
        self.ENVIARALCORREO.setObjectName("ENVIARALCORREO")
        self.CORREO = QtWidgets.QTextEdit(self.centralwidget)
        self.CORREO.setGeometry(QtCore.QRect(440, 510, 541, 31))
        self.CORREO.setStyleSheet("background-color:rgba(106, 106, 106,70);\n"
"border:none;\n"
"border-bottom:2px goldrgba(5,5,5,10);\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:5px;\n"
"")
        self.CORREO.setObjectName("CORREO")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Smart Farm Len"))
        self.enfermedades.setText(_translate("MainWindow", "    Enfermedades"))
        self.plagas.setText(_translate("MainWindow", "      Plagas"))
        self.mostrar_con.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial Rounded MT Bold\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.adjuntar.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Adjuntar</span></p></body></html>"))
        self.adjuntar.setText(_translate("MainWindow", "Adjuntar"))
        self.predecir.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Adjuntar</span></p></body></html>"))
        self.predecir.setText(_translate("MainWindow", "Predecir"))
        self.eliminar.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Adjuntar</span></p></body></html>"))
        self.eliminar.setText(_translate("MainWindow", "Eliminar"))
        self.imagen.setText(_translate("MainWindow", "TextLabel"))
        self.Regresar.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Adjuntar</span></p></body></html>"))
        self.Regresar.setText(_translate("MainWindow", "REGRESAR"))
        self.ENVIARALCORREO.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Adjuntar</span></p></body></html>"))
        self.ENVIARALCORREO.setText(_translate("MainWindow", "Enviar"))
from IMAGENES import source2


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow3()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
